### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by Haschtl** [mickidum/public-woo-api#1]
WooCommerce: Version 4.8.0

I have installed this plugin directly from wordpress.
I can access the WooCommerce API via GET requests with autentification (`/wp-json/wc/v3/`).
But I cannot access it without authentification at `/wp-json/public-woo/v1/`
I also noticed, that there was no communication with the WooCommerce API as the `Last access` for this api-key in the WooCommerce settings is still `Unknown`.

**Comment by mickidum** [comment]
Checked, this works.
you need to create keys in woocommerce settings, and copy them into plugin settings form. After this should work.

read here:
https://wordpress.org/support/topic/instructions-are-not-clear/

**Comment by Haschtl** [comment]
ok, now it works... 
maybe some other wordpress plugin caused some delay
