### ISSUE TITLE
X-WP-Total & X-WP-TotalPages not present in header

### ISSUE THREAD

**Issue by Satish-Prajapati** [mickidum/public-woo-api#2]
I'm not able to find X-WP-Total & X-WP-TotalPages in header can you please add this fields

Thanks in Advance

My header response

access-control-allow-headers: Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type
access-control-expose-headers: X-WP-Total, X-WP-TotalPages, Link
allow: GET
cache-control: no-cache, must-revalidate, max-age=0
content-encoding: gzip
content-length: 12642
content-type: application/json; charset=UTF-8
date: Sat, 12 Jun 2021 07:27:22 GMT
expires: Wed, 11 Jan 1984 05:00:00 GMT
host-header: c2hhcmVkLmJsdWVob3N0LmNvbQ==
link: <https://ubonaccessories.com/wp-json/>; rel="https://api.w.org/"
server: Apache
vary: Origin,Accept-Encoding
x-content-type-options: nosniff
x-endurance-cache-level: 2
x-robots-tag: noindex

**Comment by mickidum** [comment]
added
